import LaunchSharpIcon from "@mui/icons-material/LaunchSharp";
export default function About() {
  return (
    <div className="container mx-auto m-4 p-4">
      <h1 className="text-lg text-bold pb-4">About</h1>
      <hr className="bg-blue-950 h-[3px] mb-4" />
      <p className="mb-4 pr-2">
        In 2012, the NIEHS established the multi-phased Toxicant Exposures and
        Responses by Genomic and Epigenomic Regulators of Transcription (TaRGET)
        Program to further address the role of the environment in disease
        susceptibility as a function of changes to the epigenome. The first
        phase of this program, TaRGET I (RFA-ES-12-008, TaRGET I: Chromatin
        Structure, Genomics, and Transcriptional Responses to the Environment),
        solicited and funded applications that support environmental health
        scientists' pursuit of research objectives aimed at understanding the
        environmental control of epigenetic mechanisms. These grants consider
        the impact of environmental toxicants on the following processes:
        nucleosome positioning, chromatin accessibility, chromatin remodeling
        and the role of non-coding RNAs. However, identifying exposure-induced
        changes in tissues/cells affected by disease is not always feasible in
        humans. The purpose of this Funding Opportunity Announcement is to
        establish the TaRGET II Consortium which will assess the utility of
        surrogate tissue epigenomic analysis as a means to examine the role of
        environmental exposures on epigenomic marks in target tissues.
      </p>
      <p className="mb-4 pr-2">
        The goals are to enhance our understanding of the relationship between
        exposure-induced perturbations of epigenetic marks in target versus
        surrogate tissues; determine conditions where these studies will be
        valid; and aid in the interpretation of the results of such studies.
        Applications submitted in response to this FOA must propose aims that
        focus on disease relevant environmental exposures and evaluate
        epigenomic changes or patterns of changes in surrogates that may serve
        as potential biomarkers of exposure associated pathologies. This FOA is
        published in parallel with a companion FOA, RFA ES-015-002, TaRGET II:
        Environmental Epigenomics Data Coordination Center (U24). Projects
        funded by these FOAs will collectively form the TaRGET II Consortium
        (T2C) and will develop a publically accessible database that provides
        data to the broader scientific community on the conservation of
        environmental exposure induced epigenomic changes in target tissues and
        cells and selected surrogates.
      </p>

      <p className="mb-4 pr-2">
        This data portal hosts all the experimental data generated by the TaRGET
        consortium.
      </p>
      <button className="border-2 border-solid border-blue-500 px-4 rounded text-sm">
        <a href="https://www.niehs.nih.gov/research/supported/health/envepi/">
          Read More
        </a>
      </button>

      {/* Program Officers */}
      <h1 className="text-lg text-bold py-4 mt-4">Program Officers</h1>
      <hr className="bg-blue-950 h-[3px] mb-4" />
      <ul class="list-disc list-outside p-4 ">
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://www.niehs.nih.gov/research/supported/dert/geh/tyson/index.cfm"
          >
            Fred Tyson, PhD <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://www.niehs.nih.gov/research/supported/dert/geh/mcallister/index.cfm"
          >
            Kim McAllister, PhD
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://www.niehs.nih.gov/research/supported/dert/geh/duncan/index.cfm"
          >
            Christopher G. Duncan, PhD
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://www.niehs.nih.gov/research/supported/dert/geh/garton/index.cfm"
          >
            Amanda Garton
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://www.genome.gov/staff/Lisa-Helbling-Chadwick-PhD"
          >
            Lisa H. Chadwick, PhD
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
      </ul>

      {/* Consortium Investigators */}
      <h1 className="text-lg text-bold py-4 mt-4">Consortium Investigators</h1>
      <hr className="bg-blue-950 h-[3px] mb-4" />
      <ul class="list-disc list-outside p-4 ">
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://aylorlab.wordpress.ncsu.edu/"
          >
            David Aylor, Ph.D ~ North Carolina State University
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="http://www.med.upenn.edu/apps/faculty/index.php/g20001500/p13534"
          >
            Marisa S. Bartolomei, Ph.D ~ University of Pennsylvania
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://www.jhsph.edu/faculty/directory/profile/979/shyam-s-biswal"
          >
            Shyam S. Biswal, Ph.D ~ Johns Hopkins University
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://sph.umich.edu/faculty-profiles/dolinoy-dana.html"
          >
            Dana Dolinoy, Ph.D ~ University of Michigan{" "}
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="http://www.uchospitals.edu/physicians/gokhan-mutlu.html"
          >
            Gokhan Mutlu, MD ~ University of Chicago
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://case.edu/medicine/cvri/people/sanjay-rajagopalan"
          >
            Sanjay Rajagopalan, MD ~ Case Western Reserve University
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://www.bcm.edu/centers/precision-environmental-health"
          >
            Cheryl Walker, PhD ~ Baylor College of Medicine
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://ehe.jhu.edu/research/faculty-research-interests/wang/"
          >
            Zhibin Wang, PhD ~ Johns Hopkins University
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
      </ul>

      {/* Data Coordination Center Investigators */}
      <h1 className="text-lg text-bold py-4 mt-4">
        Data Coordination Center (DCC) - Investigators
      </h1>
      <hr className="bg-blue-950 h-[3px] mb-4" />
      <ul class="list-disc list-outside p-4 ">
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="http://wang.wustl.edu/"
          >
            Ting Wang, PhD ~ Washington University in St. Louis
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="https://genetics.wustl.edu/people/michael-province-phdprofessor-and-director-division-of-statistical-genetics-dsg/"
          >
            Michael Province, PhD ~ Washington University in St. Louis
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="http://devbio.wustl.edu/faculty/faculty-members/bo-zhang-ph.d"
          >
            Bo Zhang, PhD ~ Washington University in St. Louis
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
        <li>
          <a
            className="pr-2 hover:underline hover:underline-offset-4 hover:decoration-rose-500 hover:decoration-2"
            href="http://lawsonlab.wustl.edu/"
          >
            Heather Lawson, PhD ~ Washington University in St. Louis
            <LaunchSharpIcon fontSize="small" color="primary" />
          </a>
        </li>
      </ul>

      <h1 className="text-lg text-bold py-4 mt-4">
        Data Portal Team - Washington University School of Medicine in St. Louis
      </h1>
      <hr className="bg-blue-950 h-[3px] mb-4" />
      <ul class="list-disc list-outside p-4 ">
        <li>Prashant Kumar Kuntala ~ Developer</li>
        <li>Deepak Purushotham ~ Developer</li>
        <li>Daofeng Li ~ Developer</li>
        <li>Xiaoyu Zhuo ~ Developer</li>
        <li>Silas Hsu ~ Developer</li>
        <li>Benpeng Miao ~ Data Curator</li>
        <li>Juheon Maeng ~ Data Curator</li>
        <li>Yujie Chen ~ Data Curator</li>
        <li>Alan Du ~ Data Curator</li>
        <li>Yiran Hou ~ Data Curator</li>
        <li>Wanqing Shao ~ Data Curator</li>
      </ul>

      <hr className="bg-blue-950 h-[3px] mb-4" />
      <p className="mb-4 pr-2">
        The TaRGET DCC is funded by a U24 grant from the National Institute of
        Environmental Health Sciences at the U.S. National Institutes of Health.
        The content of this web site is solely the responsibility of the
        contributors and does not necessarily represent the official views of
        the National Institute of Environmental Health Sciences or the National
        Institutes of Health.
      </p>
      <button className="border-2 border-solid border-blue-500 px-2 rounded m-1">
        <a href="https://grants.nih.gov/grants/guide/rfa-files/RFA-ES-15-001.html">
          TaRGET II: Environmental Epigenomic Analysis in Tissue Surrogates
          (U01) <LaunchSharpIcon fontSize="small" color="primary" />
        </a>
      </button>
      <button className="border-2 border-solid border-blue-500 px-2 rounded m-1">
        <a href="https://grants.nih.gov/grants/guide/rfa-files/RFA-ES-15-002.html">
          TaRGET II: Environmental Epigenomics Data Coordination Center (U24){" "}
          <LaunchSharpIcon fontSize="small" color="primary" />
        </a>
      </button>
      <button className="border-2 border-solid border-blue-500 px-2 rounded m-1">
        <a href="https://doi.org/10.1038/nbt.4099">
          TaRGET II: White Paper
          <LaunchSharpIcon fontSize="small" color="primary" />
        </a>
      </button>
    </div>
  );
}
